[workspace]
[package]
name = "stdweb-example"
version = "0.1.0"
authors = ["Jakob Meier <mail@jakobmeier.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nuts = { path = "../../" }
stdweb = "0.4.20"